Repository Adregamdi/Backend, pull requests merged in 2024-08, with the labels that each got.

#31 Refactor - 로그인 기능 수정
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/oauth2/dto/ApplePublicKey.java
  src/main/java/com/adregamdi/core/oauth2/dto/LoginRequest.java
  src/main/java/com/adregamdi/core/oauth2/dto/LoginResponse.java
  src/main/java/com/adregamdi/core/oauth2/presentation/OAuth2Controller.java
  src/main/java/com/adregamdi/core/oauth2/service/OAuth2Service.java
  src/main/java/com/adregamdi/member/application/MemberService.java
Labels: 🔨 Refactor, 📬 API

#34 Feature - 장소 관련 기능 구현
  src/main/generated/com/adregamdi/member/domain/QMember.java
  src/main/generated/com/adregamdi/notification/domain/QNotification.java
  src/main/generated/com/adregamdi/place/domain/QPlace.java
  src/main/generated/com/adregamdi/schedule/domain/QSchedule.java
  src/main/generated/com/adregamdi/schedule/domain/QSchedulePlace.java
  src/main/java/com/adregamdi/core/constant/Constant.java
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/core/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adregamdi/core/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/adregamdi/core/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/adregamdi/core/oauth2/service/OAuth2Service.java
  src/main/java/com/adregamdi/core/utils/PageUtil.java
  src/main/java/com/adregamdi/core/utils/RepositoryUtil.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/member/infrastructure/MemberRepository.java
  src/main/java/com/adregamdi/member/presentation/MemberController.java
  src/main/java/com/adregamdi/notification/application/NotificationService.java
  src/main/java/com/adregamdi/notification/domain/Notification.java
  src/main/java/com/adregamdi/notification/dto/NotificationDTO.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationCustomRepositoryImpl.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/domain/Place.java
  src/main/java/com/adregamdi/place/dto/PlaceDTO.java
  src/main/java/com/adregamdi/place/dto/request/CreatePlaceRequest.java
  src/main/java/com/adregamdi/place/dto/response/GetPlaceResponse.java
  src/main/java/com/adregamdi/place/dto/response/GetPlacesResponse.java
  src/main/java/com/adregamdi/place/exception/PlaceException.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepository.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepositoryImpl.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceRepository.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
  src/main/java/com/adregamdi/schedule/application/ScheduleService.java
  src/main/java/com/adregamdi/schedule/domain/Schedule.java
  src/main/java/com/adregamdi/schedule/domain/SchedulePlace.java
  src/main/java/com/adregamdi/schedule/dto/request/CreateMyScheduleRequest.java
  src/main/java/com/adregamdi/schedule/exception/ScheduleException.java
  src/main/java/com/adregamdi/schedule/infrastructure/ScheduleCustomRepository.java
  src/main/java/com/adregamdi/schedule/infrastructure/ScheduleCustomRepositoryImpl.java
  src/main/java/com/adregamdi/schedule/infrastructure/SchedulePlaceRepository.java
  src/main/java/com/adregamdi/schedule/infrastructure/ScheduleRepository.java
  src/main/java/com/adregamdi/schedule/presentation/ScheduleController.java
Labels: ✨ Feature, 📬 API

#41 [#28] 쇼츠 도메인 구현
  build.gradle
  src/main/generated/com/adregamdi/shorts/domain/QShorts.java
  src/main/java/com/adregamdi/core/config/AWSS3Config.java
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/core/utils/SecureStringUtil.java
  src/main/java/com/adregamdi/media/application/FileUploadService.java
  src/main/java/com/adregamdi/media/application/ImageService.java
  src/main/java/com/adregamdi/media/application/S3StorageService.java
  src/main/java/com/adregamdi/shorts/application/ShortsService.java
  src/main/java/com/adregamdi/shorts/application/ShortsServiceImpl.java
  src/main/java/com/adregamdi/shorts/application/ShortsValidService.java
  src/main/java/com/adregamdi/shorts/application/VideoService.java
  src/main/java/com/adregamdi/shorts/application/VideoValidateService.java
  src/main/java/com/adregamdi/shorts/domain/Shorts.java
  src/main/java/com/adregamdi/shorts/dto/ShortsDTO.java
  src/main/java/com/adregamdi/shorts/dto/request/CreateShortsRequest.java
  src/main/java/com/adregamdi/shorts/dto/request/UpdateShortsRequest.java
  src/main/java/com/adregamdi/shorts/dto/response/CreateShortsResponse.java
  src/main/java/com/adregamdi/shorts/dto/response/GetShortsResponse.java
  src/main/java/com/adregamdi/shorts/dto/response/SaveVideoResponse.java
  src/main/java/com/adregamdi/shorts/dto/response/UploadVideoDTO.java
  src/main/java/com/adregamdi/shorts/exception/ShortsException.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepository.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsRepository.java
  src/main/java/com/adregamdi/shorts/presentation/ShortsController.java
Labels: ✨ Feature

#45 Feature - 일정 관련된 API 구현
  build.gradle
  src/main/generated/com/adregamdi/schedule/domain/QSchedule.java
  src/main/generated/com/adregamdi/schedule/domain/QSchedulePlace.java
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/core/oauth2/presentation/OAuth2Controller.java
  src/main/java/com/adregamdi/notification/presentation/NotificationController.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/schedule/application/ScheduleService.java
  src/main/java/com/adregamdi/schedule/domain/Schedule.java
  src/main/java/com/adregamdi/schedule/domain/SchedulePlace.java
  src/main/java/com/adregamdi/schedule/dto/ScheduleDTO.java
  src/main/java/com/adregamdi/schedule/dto/ScheduleListDTO.java
  src/main/java/com/adregamdi/schedule/dto/request/CreateMyScheduleRequest.java
  src/main/java/com/adregamdi/schedule/dto/request/GetMyScheduleRequest.java
  src/main/java/com/adregamdi/schedule/dto/response/GetMyScheduleResponse.java
  src/main/java/com/adregamdi/schedule/exception/ScheduleException.java
  src/main/java/com/adregamdi/schedule/infrastructure/SchedulePlaceRepository.java
  src/main/java/com/adregamdi/schedule/infrastructure/ScheduleRepository.java
  src/main/java/com/adregamdi/schedule/presentation/ScheduleController.java
Labels: ✨ Feature, 📬 API

#47 Refactor - 알림 인터페이스 구현
  src/main/generated/com/adregamdi/notification/domain/QNotification.java
  src/main/java/com/adregamdi/notification/application/NotificationService.java
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
  src/main/java/com/adregamdi/notification/domain/Notification.java
  src/main/java/com/adregamdi/notification/domain/NotificationType.java
  src/main/java/com/adregamdi/notification/dto/request/CreateNotificationRequest.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationCustomRepository.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationCustomRepositoryImpl.java
Labels: 🔨 Refactor, ✨ Feature

#49 Refactor - 회원 관련된 기능들 수정
  src/main/java/com/adregamdi/core/oauth2/dto/OAuth2Attributes.java
  src/main/java/com/adregamdi/core/oauth2/dto/SignUpDTO.java
  src/main/java/com/adregamdi/core/oauth2/service/AppleOAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/service/GoogleOAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/service/KakaoOAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/service/OAuth2UserInfo.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/member/dto/request/UpdateMyMemberRequest.java
  src/main/java/com/adregamdi/member/dto/response/GetMyMemberResponse.java
  src/main/java/com/adregamdi/member/presentation/MemberController.java
Labels: 🔨 Refactor, ✨ Feature, 📬 API

#56 [#55] jar 파일 실행 후 상태 체크 추가
  .github/workflows/pr-build-gradle-dev.yml
  .github/workflows/push-deploy-dev.yml
Labels: 🐞 BugFix
