Repository Adregamdi/Backend, pull requests merged in 2024-07, with the labels that each got.

#16 Feature - 구글, 카카오 로그인 구현
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adregamdi/core/oauth2/domain/CustomOAuth2User.java
  src/main/java/com/adregamdi/core/oauth2/dto/ApplePublicKey.java
  src/main/java/com/adregamdi/core/oauth2/dto/OAuth2Attributes.java
  src/main/java/com/adregamdi/core/oauth2/dto/SignUpDTO.java
  src/main/java/com/adregamdi/core/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/adregamdi/core/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/adregamdi/core/oauth2/service/AppleOAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/adregamdi/core/oauth2/service/GoogleOAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/service/KakaoOAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/service/OAuth2UserInfo.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/member/domain/SocialType.java
  src/main/java/com/adregamdi/member/exception/MemberException.java
  src/main/java/com/adregamdi/member/infrastructure/MemberRepository.java
  src/main/resources/static/index.html
Labels: ✨ Feature

#18 Chore - 빌드 설정 추가
  build.gradle
  src/test/java/com/adregamdi/AdregamdiApplicationTests.java
Labels: ⚙ Setting

#19 Feature - 로그아웃, 회원탈퇴 구현
  build.gradle
  src/main/java/com/adregamdi/core/config/WebClientConfig.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/member/infrastructure/MemberRepository.java
  src/main/java/com/adregamdi/member/presentation/MemberController.java
Labels: ✨ Feature

#20 [#13] Chore - 배포 자동화 CI/CD 설정
  .github/workflows/push-deploy.yml
Labels: ⚙ Setting, ✨ Feature

#24 [#23] Bugfix - 배포 오류 해결
  .github/workflows/push-deploy.yml
Labels: 🐞 BugFix

#25 Feature - 특정 회원 조회 API 구현
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/dto/response/GetMyMemberResponse.java
  src/main/java/com/adregamdi/member/presentation/MemberController.java
Labels: ✨ Feature, 📬 API

#26 Feature - QueryDSL 세팅, 알림 관련 API 구현
  build.gradle
  src/main/generated/com/adregamdi/core/entity/QBaseTime.java
  src/main/generated/com/adregamdi/member/domain/QMember.java
  src/main/generated/com/adregamdi/notification/domain/QNotification.java
  src/main/java/com/adregamdi/core/config/QueryDSLConfig.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/notification/application/NotificationService.java
  src/main/java/com/adregamdi/notification/domain/Notification.java
  src/main/java/com/adregamdi/notification/domain/NotificationType.java
  src/main/java/com/adregamdi/notification/dto/NotificationDTO.java
  src/main/java/com/adregamdi/notification/dto/request/UpdateNotificationRequest.java
  src/main/java/com/adregamdi/notification/dto/response/GetNotificationResponse.java
  src/main/java/com/adregamdi/notification/exception/NotificationException.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationCustomRepository.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationCustomRepositoryImpl.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationRepository.java
  src/main/java/com/adregamdi/notification/presentation/NotificationController.java
Labels: ⚙ Setting, ✨ Feature, 📬 API
