Repository Adregamdi/Backend, pull requests merged in 2024-06, with the labels that each got.

#2 Feature - 코어 기능 세팅
  src/main/java/com/adregamdi/AdregamdiApplication.java
  src/main/java/com/adregamdi/core/config/CorsProperties.java
  src/main/java/com/adregamdi/core/config/WebConfig.java
  src/main/java/com/adregamdi/core/entity/BaseTime.java
  src/main/java/com/adregamdi/core/handler/ApiResponse.java
  src/main/java/com/adregamdi/core/handler/ErrorResponse.java
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
Labels: Feature

#4 Bugfix - 예외 애노테이션 충돌 버그 수정
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
Labels: Bugfix

#6 Update issue templates
  .github/ISSUE_TEMPLATE/⚙️chore-issue-template.md
  .github/ISSUE_TEMPLATE/✂️refactoring-issue-template.md
  .github/ISSUE_TEMPLATE/✅feature-issue-template.md
  .github/ISSUE_TEMPLATE/🐞bugfix-issue-template.md
  .github/ISSUE_TEMPLATE/📒docs-issue-template.md
Labels: 📃 Docs

#8 [#7] Docs - PR 템플릿 적용
  .github/pull_request_template.md
Labels: 📃 Docs

#9 Feature - AOP 로깅, 스프링 시큐리티 설정
  build.gradle
  src/main/java/com/adregamdi/core/annotation/AdminAuthorize.java
  src/main/java/com/adregamdi/core/annotation/MemberAuthorize.java
  src/main/java/com/adregamdi/core/aop/LogAspect.java
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/exception/GlobalException.java
  src/main/java/com/adregamdi/core/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adregamdi/core/jwt/service/JwtService.java
  src/main/java/com/adregamdi/core/utils/PasswordUtil.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/member/domain/Role.java
  src/main/java/com/adregamdi/member/exception/MemberException.java
  src/main/java/com/adregamdi/member/infrastructure/MemberRepository.java
Labels: ✨ Feature

#12 [#11] Chore : 2024-06-27 issue branch 자동 생성 ci 설정
  .github/issue-branch.yml
  .github/workflows/make-issue-branch.yml
Labels: 🔨 Refactor
