Repository Adregamdi/Backend, pull requests merged in 2024-10, with the labels that each got.

#199 Refactor - 토큰 예외 추가
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/exception/GlobalException.java
  src/main/java/com/adregamdi/core/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adregamdi/core/jwt/service/JwtService.java
Labels: 🔨 Refactor

#201 BugFix - 토큰 처리 과정 버그 수정
  src/main/java/com/adregamdi/core/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adregamdi/core/jwt/service/JwtService.java
Labels: 🐞 BugFix

#203 Feature - 일정/여행기 삭제 API 구현
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/presentation/TravelController.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueRepository.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: ✨ Feature, 📬 API

#206 Refactor - 알림 조회/등록 관련 수정
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/notification/application/NotificationService.java
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
  src/main/java/com/adregamdi/notification/domain/ContentType.java
  src/main/java/com/adregamdi/notification/domain/Notification.java
  src/main/java/com/adregamdi/notification/domain/NotificationType.java
  src/main/java/com/adregamdi/notification/dto/NotificationDTO.java
  src/main/java/com/adregamdi/notification/dto/request/CreateNotificationRequest.java
  src/main/java/com/adregamdi/notification/presentation/NotificationController.java
Labels: 🔨 Refactor, 📬 API

#208 [#207] 대소문자 비교 대신 enumType 비교로 수정
  src/main/java/com/adregamdi/like/application/LikesService.java
Labels: 🐞 BugFix

#211 Bugfix - 일정/여행기 삭제 시 자식 데이터 삭제 안 되던 버그 수정
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueDayPlaceReviewRepository.java
Labels: 🐞 BugFix

#213 [#212][Chore] ssh 포트 추가
  .github/workflows/push-deploy-dev.yml
  .github/workflows/push-deploy-prod.yml
Labels: ⚙ Setting

#214 Refactoring - 예외 처리 및 로깅 개선
  src/main/java/com/adregamdi/core/aop/LogAspect.java
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
Labels: 🔨 Refactor, 🗨️ Comment, 📬 API

#218 [#215] 특정 회원의 컨텐츠 리스트 조회
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/SelectedType.java
  src/main/java/com/adregamdi/member/dto/AllContentDTO.java
  src/main/java/com/adregamdi/member/dto/request/GetMemberContentsRequest.java
  src/main/java/com/adregamdi/member/dto/response/GetMemberContentsResponse.java
  src/main/java/com/adregamdi/member/infrastructure/MemberCustomRepository.java
  src/main/java/com/adregamdi/member/infrastructure/MemberCustomRepositoryImpl.java
  src/main/java/com/adregamdi/member/infrastructure/MemberRepository.java
  src/main/java/com/adregamdi/member/presentation/MemberController.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceReviewRepository.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
  src/main/java/com/adregamdi/shorts/presentation/ShortsController.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetMemberTraveloguesResponse.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepository.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: ✨ Feature

#219 Refactoring - 회원 탈퇴 시 해당 회원과 관련된 콘텐츠 데이터 제거
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/like/infrastructure/LikesRepository.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/infrastructure/MemberRepository.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceReviewRepository.java
  src/main/java/com/adregamdi/shorts/application/ShortsService.java
  src/main/java/com/adregamdi/shorts/application/ShortsServiceImpl.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsRepository.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueRepository.java
Labels: 🔨 Refactor, ✨ Feature

#222 Refactor - 서비스 클래스 추상화
  src/main/java/com/adregamdi/block/application/BlockService.java
  src/main/java/com/adregamdi/block/application/BlockServiceImpl.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/application/MemberServiceImpl.java
  src/main/java/com/adregamdi/notification/application/NotificationService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/search/application/SearchService.java
  src/main/java/com/adregamdi/search/application/SearchServiceImpl.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/application/TravelServiceImpl.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueServiceImpl.java
Labels: 🔨 Refactor

#224 Refactoring - 알림 조회 API 응답에 콘텐츠 id 추가
  src/main/generated/com/adregamdi/notification/domain/QNotification.java
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
  src/main/java/com/adregamdi/notification/domain/Notification.java
  src/main/java/com/adregamdi/notification/dto/NotificationDTO.java
  src/main/java/com/adregamdi/notification/dto/request/CreateNotificationRequest.java
Labels: 🔨 Refactor, 📬 API

#226 Feature - 특정 쇼츠 조회 API 구현
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/member/application/MemberServiceImpl.java
  src/main/java/com/adregamdi/member/dto/ShortsWithMemberDTO.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/dto/response/GetPlaceResponse.java
  src/main/java/com/adregamdi/shorts/application/ShortsService.java
  src/main/java/com/adregamdi/shorts/application/ShortsServiceImpl.java
  src/main/java/com/adregamdi/shorts/dto/ShortsDTO.java
  src/main/java/com/adregamdi/shorts/dto/response/GetShortsByShortsIdResponse.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsRepository.java
  src/main/java/com/adregamdi/shorts/presentation/ShortsController.java
Labels: ✨ Feature, 📬 API

#228 BugFix - 특정 쇼츠 조회 안 되던 버그 수정
  src/main/java/com/adregamdi/shorts/application/ShortsServiceImpl.java
Labels: 🐞 BugFix, 📬 API

#230 Refactor - 여행기 생성 시 날짜 별 메모 추가
  src/main/java/com/adregamdi/member/infrastructure/MemberRepository.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationRepository.java
  src/main/java/com/adregamdi/travel/application/TravelServiceImpl.java
  src/main/java/com/adregamdi/travel/infrastructure/TravelDayRepository.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueServiceImpl.java
  src/main/java/com/adregamdi/travelogue/domain/TravelogueDay.java
  src/main/java/com/adregamdi/travelogue/dto/request/CreateMyTravelogueRequest.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetTravelogueResponse.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueDayRepository.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueImageRepository.java
Labels: 🔨 Refactor, 📬 API

#232 Feature - 중복 알림 버그를 위한 알림 삭제 기능 구현 등
  src/main/generated/com/adregamdi/like/domain/QLike.java
  src/main/generated/com/adregamdi/notification/domain/QNotification.java
  src/main/generated/com/adregamdi/travelogue/domain/QTravelogueDay.java
  src/main/java/com/adregamdi/block/application/BlockService.java
  src/main/java/com/adregamdi/core/constant/ContentType.java
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/like/domain/Like.java
  src/main/java/com/adregamdi/like/domain/enumtype/SelectedType.java
  src/main/java/com/adregamdi/like/dto/AllContentDTO.java
  src/main/java/com/adregamdi/like/dto/request/CreateLikesRequest.java
  src/main/java/com/adregamdi/like/dto/request/DeleteLikeRequest.java
  src/main/java/com/adregamdi/like/dto/request/GetLikesContentsRequest.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepository.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/like/infrastructure/LikesRepository.java
  src/main/java/com/adregamdi/like/presentation/LikesController.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/notification/application/NotificationService.java
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
  src/main/java/com/adregamdi/notification/domain/ContentType.java
  src/main/java/com/adregamdi/notification/domain/Notification.java
  src/main/java/com/adregamdi/notification/dto/NotificationDTO.java
  src/main/java/com/adregamdi/notification/dto/request/CreateNotificationRequest.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationRepository.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/search/application/SearchService.java
  src/main/java/com/adregamdi/search/application/SearchServiceImpl.java
  src/main/java/com/adregamdi/search/dto/SearchType.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/search/presentation/SearchController.java
  src/main/java/com/adregamdi/shorts/application/ShortsService.java
  src/main/java/com/adregamdi/shorts/application/ShortsServiceImpl.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueServiceImpl.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
Labels: 🔨 Refactor, ✨ Feature, 📬 API

#234 BugFix - 알림 데이터 삭제 시 여러 데이터 조회 버그 수정
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/notification/application/NotificationService.java
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationRepository.java
Labels: 🐞 BugFix

#236 BugFix - 알림 조회 시 첫 페이지 데이터만 조회되던 버그 수정
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
  src/main/java/com/adregamdi/notification/dto/NotificationPageResult.java
  src/main/java/com/adregamdi/notification/dto/response/GetNotificationResponse.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationCustomRepository.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationCustomRepositoryImpl.java
Labels: 🐞 BugFix, 📬 API

#238 Refactoring - 요청 파람 name 설정
  src/main/java/com/adregamdi/notification/presentation/NotificationController.java
Labels: 🔨 Refactor

#240 BugFix - 좋아요/알림 삭제 안 되던 버그 수정
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
Labels: 🐞 BugFix, 📬 API

#242 Refactoring - 내가 내 콘텐츠에서 발생시킨 알림 데이터 관련 수정
  src/main/generated/com/adregamdi/notification/domain/QNotification.java
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
  src/main/java/com/adregamdi/notification/domain/Notification.java
  src/main/java/com/adregamdi/notification/dto/NotificationDTO.java
  src/main/java/com/adregamdi/notification/dto/request/CreateNotificationRequest.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationRepository.java
Labels: 🔨 Refactor

#244 Refactoring - 알림 데이터가 존재할 경우만 삭제하도록 수정
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
Labels: 🔨 Refactor

#246 Refactor - 접속 시간 체크 메서드 사용 위치 수정
  src/main/java/com/adregamdi/core/jwt/service/JwtService.java
  src/main/java/com/adregamdi/core/oauth2/application/OAuth2Service.java
Labels: 🔨 Refactor

#248 Refactor - 인기 장소 리스트 조회 캐싱 방식으로 수정
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adregamdi/core/jwt/service/JwtService.java
  src/main/java/com/adregamdi/core/oauth2/application/OAuth2Service.java
  src/main/java/com/adregamdi/core/redis/application/TokenRedisService.java
  src/main/java/com/adregamdi/member/application/MemberServiceImpl.java
  src/main/java/com/adregamdi/place/application/PlaceRedisService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
Labels: 🔨 Refactor, 📬 API

#251 Bugfix - 장소 추가 시 카운트 변동 안 되던 버그 수정
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
Labels: 🐞 BugFix

#253 Refactor - 인기 장소 조회 쿼리 수정, 일정 생성 시 예외 처리 추가
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travel/application/TravelServiceImpl.java
  src/main/java/com/adregamdi/travel/exception/TravelException.java
Labels: 🔨 Refactor, 📬 API

#255 Bugfix - 인기 장소 조회 쿼리 버그 수정
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepositoryImpl.java
Labels: 🐞 BugFix

#257 Refactor - 인기 장소 캐시 업데이트 로그 추가
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
Labels: 🔨 Refactor

#258 Refactor - 공통 기능 분리 및 가독성 리팩토링 등
  src/main/java/com/adregamdi/block/application/BlockServiceImpl.java
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/member/application/MemberServiceImpl.java
  src/main/java/com/adregamdi/member/exception/MemberException.java
  src/main/java/com/adregamdi/notification/application/NotificationServiceImpl.java
  src/main/java/com/adregamdi/search/application/SearchServiceImpl.java
  src/main/java/com/adregamdi/travel/application/TravelServiceImpl.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueServiceImpl.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: 🔨 Refactor
