Repository Adregamdi/Backend, pull requests merged in 2024-09, with the labels that each got.

#59 Refactor - 일정, 여행기 응답 수정
  src/main/java/com/adregamdi/travel/dto/response/GetMyTravelResponse.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetTravelogueResponse.java
Labels: 🔨 Refactor

#60 Refactor - 검색 API 전면 리팩토링
  src/main/java/com/adregamdi/search/application/SearchService.java
  src/main/java/com/adregamdi/search/dto/SearchItemDTO.java
  src/main/java/com/adregamdi/search/dto/SearchType.java
  src/main/java/com/adregamdi/search/dto/response/SearchResponse.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepository.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/search/presentation/SearchController.java
Labels: 🔨 Refactor, ✨ Feature, 📬 API

#62 [#50] 이미지 API 구현
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/media/application/ImageService.java
  src/main/java/com/adregamdi/media/application/ImageServiceImpl.java
  src/main/java/com/adregamdi/media/application/ImageValidService.java
  src/main/java/com/adregamdi/media/domain/Image.java
  src/main/java/com/adregamdi/media/domain/ImageTarget.java
  src/main/java/com/adregamdi/media/dto/request/DeleteImagesRequest.java
  src/main/java/com/adregamdi/media/dto/response/CreateImageListResponse.java
  src/main/java/com/adregamdi/media/dto/response/CreateImageResponse.java
  src/main/java/com/adregamdi/media/exception/ImageException.java
  src/main/java/com/adregamdi/media/infrastructure/ImageRepository.java
  src/main/java/com/adregamdi/media/presentation/ImageController.java
Labels: ✨ Feature

#69 Refactor - 검색 API 수정
  src/main/java/com/adregamdi/search/application/SearchService.java
  src/main/java/com/adregamdi/search/dto/PlaceSearchDTO.java
  src/main/java/com/adregamdi/search/dto/SearchItemDTO.java
  src/main/java/com/adregamdi/search/dto/ShortsSearchDTO.java
  src/main/java/com/adregamdi/search/dto/TravelogueSearchDTO.java
  src/main/java/com/adregamdi/search/dto/response/SearchResponse.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepository.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
Labels: 🔨 Refactor, 📬 API

#72 Feature - 내 전체 일정, 내 전체 여행기 조회 API 구현
  src/main/generated/com/adregamdi/notification/domain/QNotification.java
  src/main/generated/com/adregamdi/place/domain/QPlaceReview.java
  src/main/generated/com/adregamdi/travel/domain/QTravel.java
  src/main/generated/com/adregamdi/travelogue/domain/QTravelogue.java
  src/main/java/com/adregamdi/core/utils/PageUtil.java
  src/main/java/com/adregamdi/notification/domain/Notification.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationCustomRepositoryImpl.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationRepository.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/domain/PlaceReview.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepository.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepositoryImpl.java
  src/main/java/com/adregamdi/search/application/SearchService.java
  src/main/java/com/adregamdi/search/dto/response/SearchResponse.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepository.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/search/presentation/SearchController.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/domain/Travel.java
  src/main/java/com/adregamdi/travel/domain/TravelPlace.java
  src/main/java/com/adregamdi/travel/dto/TravelDTO.java
  src/main/java/com/adregamdi/travel/dto/response/GetMyTravelsResponse.java
  src/main/java/com/adregamdi/travel/infrastructure/TravelCustomRepository.java
  src/main/java/com/adregamdi/travel/infrastructure/TravelCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travel/infrastructure/TravelRepository.java
  src/main/java/com/adregamdi/travel/presentation/TravelController.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/domain/Travelogue.java
  src/main/java/com/adregamdi/travelogue/dto/TravelogueDTO.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetMyTraveloguesResponse.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetTravelogueResponse.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepository.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueRepository.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: 🔨 Refactor, ✨ Feature, 📬 API

#74 [#73] 3회 네트워크 재시도 하도록 리팩토링
  src/main/java/com/adregamdi/shorts/presentation/ShortsController.java
Labels: 🐞 BugFix

#75 Feature - 선택 위치 기반 근처 장소 추천 API 구현
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/domain/Place.java
  src/main/java/com/adregamdi/place/dto/KorServiceApiResponse.java
  src/main/java/com/adregamdi/place/dto/KorServiceBody.java
  src/main/java/com/adregamdi/place/dto/KorServiceHeader.java
  src/main/java/com/adregamdi/place/dto/KorServiceItems.java
  src/main/java/com/adregamdi/place/dto/KorServicePlace.java
  src/main/java/com/adregamdi/place/dto/KorServiceResponse.java
  src/main/java/com/adregamdi/place/dto/response/GetSelectionBasedRecommendationPlacesResponse.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceRepository.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceReviewRepository.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
  src/main/java/com/adregamdi/search/application/SearchService.java
  src/main/java/com/adregamdi/search/dto/PlaceSearchDTO.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/travel/presentation/TravelController.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: ✨ Feature, 📬 API

#77 Bugfix - 장소 검색 안 되던 버그 수정
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
Labels: 🐞 BugFix

#81 Feature - 최적 거리 정렬 API 구현
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/dto/PlaceCoordinate.java
  src/main/java/com/adregamdi/place/dto/request/GetSortingPlacesRequest.java
  src/main/java/com/adregamdi/place/dto/response/GetSortingPlacesResponse.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
  src/main/java/com/adregamdi/place/vo/PlaceNode.java
Labels: ✨ Feature, 📬 API

#82 Feature - 회원 정보 수정 시 핸들 중복 체크 구현
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/exception/MemberException.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
Labels: ✨ Feature, 📬 API

#83 Feature - 가입 시 기본 이미지 추가
  src/main/java/com/adregamdi/member/domain/Member.java
Labels: ✨ Feature

#87 Refactor - 일정 등록/수정 API 리팩토링
  src/main/generated/com/adregamdi/travel/domain/QTravelDay.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/domain/vo/PlaceNode.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/domain/Travel.java
  src/main/java/com/adregamdi/travel/domain/TravelDay.java
  src/main/java/com/adregamdi/travel/domain/TravelPlace.java
  src/main/java/com/adregamdi/travel/dto/request/CreateMyTravelRequest.java
  src/main/java/com/adregamdi/travel/dto/response/CreateMyTravelResponse.java
  src/main/java/com/adregamdi/travel/infrastructure/TravelDayRepository.java
  src/main/java/com/adregamdi/travel/infrastructure/TravelPlaceRepository.java
  src/main/java/com/adregamdi/travel/presentation/TravelController.java
Labels: 🔨 Refactor, 📬 API

#92 Bugfix - 일정 등록/수정 API 버그 수정
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/domain/Travel.java
  src/main/java/com/adregamdi/travel/domain/TravelDay.java
Labels: 🔨 Refactor, 🐞 BugFix, 📬 API

#93 Feature - 장소 리뷰 등록 API 구현
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/domain/PlaceReview.java
  src/main/java/com/adregamdi/place/dto/request/CreatePlaceReviewRequest.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
Labels: ✨ Feature, 📬 API

#103 Refactor - 특정 일정 조회 시 제목, 위도, 경도, 라벨들 추가
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/dto/TravelPlaceDTO.java
  src/main/java/com/adregamdi/travel/dto/response/GetMyTravelResponse.java
Labels: 🔨 Refactor, ⚒️Fix, 📬 API

#107 Refactor - 여행기 api 수정
  src/main/java/com/adregamdi/member/dto/request/UpdateMyMemberRequest.java
  src/main/java/com/adregamdi/member/presentation/MemberController.java
  src/main/java/com/adregamdi/place/domain/Place.java
  src/main/java/com/adregamdi/place/domain/PlaceReview.java
  src/main/java/com/adregamdi/place/dto/response/GetPlacesResponse.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/domain/Travel.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/domain/Travelogue.java
  src/main/java/com/adregamdi/travelogue/domain/TravelogueImage.java
  src/main/java/com/adregamdi/travelogue/dto/request/CreateMyTravelogueRequest.java
  src/main/java/com/adregamdi/travelogue/dto/response/CreateMyTravelogueResponse.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueImageRepository.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: 🔨 Refactor, 📬 API

#109 [#108] userId -> memberId로 명칭 변경
  src/main/java/com/adregamdi/like/domain/Like.java
Labels: 🐞 BugFix

#110 Feature - 내 리뷰 조회 API 구현 외
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/member/dto/request/UpdateMyMemberRequest.java
  src/main/java/com/adregamdi/member/infrastructure/MemberRepository.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/dto/MyPlaceReviewDTO.java
  src/main/java/com/adregamdi/place/dto/response/GetMyPlaceReviewResponse.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceRepository.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceReviewImageRepository.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceReviewRepository.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/infrastructure/TravelPlaceRepository.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
Labels: 🐞 BugFix, ✨ Feature, 📬 API

#111 Feature - 최근 등록된 여행기 조회 API 구현
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/search/application/SearchService.java
  src/main/java/com/adregamdi/search/dto/PlaceSearchDTO.java
  src/main/java/com/adregamdi/search/dto/response/SearchResponse.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/dto/TravelogueDTO.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetRecentTraveloguesResponse.java
  src/main/java/com/adregamdi/travelogue/exception/TravelogueException.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepository.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueRepository.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: ✨ Feature, 📬 API

#113 Bugfix - 검색 안 되던 버그 수정
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
Labels: 🐞 BugFix, 📬 API

#116 Refactor - 장소 리뷰, 여행기 등록/조회 API 수정
  src/main/generated/com/adregamdi/place/domain/QPlaceReview.java
  src/main/generated/com/adregamdi/travelogue/domain/QTravelogueDayPlaceReview.java
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/domain/PlaceReview.java
  src/main/java/com/adregamdi/place/dto/request/CreatePlaceReviewRequest.java
  src/main/java/com/adregamdi/place/dto/response/CreatePlaceReviewResponse.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceReviewImageRepository.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceReviewRepository.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
  src/main/java/com/adregamdi/travel/dto/response/GetMyTravelResponse.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/domain/TravelogueDayPlaceReview.java
  src/main/java/com/adregamdi/travelogue/dto/request/CreateMyTravelogueRequest.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetTravelogueResponse.java
  src/main/java/com/adregamdi/travelogue/exception/TravelogueException.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueDayPlaceReviewRepository.java
Labels: 🔨 Refactor, 📬 API

#121 [#96] 좋아요 api 리팩토링
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/like/domain/Like.java
  src/main/java/com/adregamdi/like/dto/response/CreateLikesResponse.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepository.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/like/presentation/LikesController.java
  src/main/java/com/adregamdi/shorts/dto/ShortsDTO.java
Labels: 🔨 Refactor, 🐞 BugFix

#123 [#122] 이미지 업데이트 리팩토링
  src/main/java/com/adregamdi/media/application/ImageService.java
  src/main/java/com/adregamdi/media/application/ImageServiceImpl.java
  src/main/java/com/adregamdi/media/infrastructure/ImageRepository.java
Labels: 🔨 Refactor

#127 Refactor - 일정 조회 API 수정, 장소 저장/조회 시 수정, 좋아요 여부 추가
  src/main/generated/com/adregamdi/place/domain/QPlace.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/domain/Place.java
  src/main/java/com/adregamdi/place/dto/PlaceDTO.java
  src/main/java/com/adregamdi/place/dto/response/GetPlaceResponse.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceReviewRepository.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/dto/TravelPlaceDTO.java
  src/main/java/com/adregamdi/travel/dto/response/GetMyTravelResponse.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetTravelogueResponse.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: 🔨 Refactor, ✨ Feature, 📬 API

#128 [#124] 쇼츠 조회 시 유저 정보 추가, 좋아요 총 개수 추가
  src/main/java/com/adregamdi/like/dto/ShortsContentDTO.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/search/application/SearchService.java
  src/main/java/com/adregamdi/search/dto/ShortsSearchDTO.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepository.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/search/presentation/SearchController.java
  src/main/java/com/adregamdi/shorts/dto/ShortsDTO.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
  src/main/java/com/adregamdi/shorts/presentation/ShortsController.java
Labels: 🔨 Refactor

#130 [#124] 랜덤 보안 문자 발생기 문자 조정
  src/main/java/com/adregamdi/core/utils/SecureStringUtil.java
  src/main/java/com/adregamdi/media/application/S3StorageService.java
Labels: 🔨 Refactor

#133 [#132] 좋아요 삭제 API 수정
  src/main/java/com/adregamdi/like/dto/request/DeleteLikeRequest.java
  src/main/java/com/adregamdi/like/presentation/LikesController.java
Labels: 🐞 BugFix

#134 Feature - 애플 로그인 구현 외
  build.gradle
  src/main/generated/com/adregamdi/like/domain/QLike.java
  src/main/generated/com/adregamdi/media/domain/QImage.java
  src/main/generated/com/adregamdi/notification/domain/QNotification.java
  src/main/generated/com/adregamdi/place/domain/QPlaceReview.java
  src/main/generated/com/adregamdi/shorts/domain/QShorts.java
  src/main/generated/com/adregamdi/travel/domain/QTravel.java
  src/main/generated/com/adregamdi/travelogue/domain/QTravelogue.java
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/core/oauth2/application/AppleOAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/application/CustomOAuth2UserService.java
  src/main/java/com/adregamdi/core/oauth2/application/GoogleOAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/application/KakaoOAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/application/OAuth2Service.java
  src/main/java/com/adregamdi/core/oauth2/application/OAuth2UserInfo.java
  src/main/java/com/adregamdi/core/oauth2/dto/LoginRequest.java
  src/main/java/com/adregamdi/core/oauth2/dto/OAuth2Attributes.java
  src/main/java/com/adregamdi/core/oauth2/presentation/OAuth2Controller.java
  src/main/java/com/adregamdi/core/oauth2/service/OAuth2Service.java
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/like/domain/Like.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepository.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/media/application/ImageServiceImpl.java
  src/main/java/com/adregamdi/media/domain/Image.java
  src/main/java/com/adregamdi/media/infrastructure/ImageRepository.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/member/dto/request/UpdateMyMemberRequest.java
  src/main/java/com/adregamdi/notification/domain/Notification.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationCustomRepositoryImpl.java
  src/main/java/com/adregamdi/notification/infrastructure/NotificationRepository.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/domain/PlaceReview.java
  src/main/java/com/adregamdi/place/dto/MyPlaceReviewDTO.java
  src/main/java/com/adregamdi/place/dto/PlaceReviewDTO.java
  src/main/java/com/adregamdi/place/dto/request/CreatePlaceReviewRequest.java
  src/main/java/com/adregamdi/place/dto/response/GetPlaceReviewResponse.java
  src/main/java/com/adregamdi/place/exception/PlaceException.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceReviewRepository.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
  src/main/java/com/adregamdi/search/application/SearchService.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepository.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/shorts/application/ShortsServiceImpl.java
  src/main/java/com/adregamdi/shorts/domain/Shorts.java
  src/main/java/com/adregamdi/shorts/dto/response/CreateShortsResponse.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepository.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsRepository.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/domain/Travel.java
  src/main/java/com/adregamdi/travel/infrastructure/TravelCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travel/infrastructure/TravelRepository.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/domain/Travelogue.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
Labels: 🔨 Refactor, 🐞 BugFix, ✨ Feature, 📬 API

#136 Feature - 관리자용 토큰 발급 api 구현
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/jwt/service/JwtService.java
  src/main/java/com/adregamdi/core/oauth2/presentation/OAuth2Controller.java
Labels: ✨ Feature, 📬 API

#139 [#138] memberId 데이터 타입 변경
  src/main/java/com/adregamdi/like/dto/ShortsContentDTO.java
  src/main/java/com/adregamdi/search/dto/ShortsSearchDTO.java
  src/main/java/com/adregamdi/shorts/dto/ShortsDTO.java
Labels: 🐞 BugFix

#140 [#138] 쇼츠 리스트 조회 버그 픽스
  build.gradle
  src/main/java/com/adregamdi/like/application/LikesService.java
  src/main/java/com/adregamdi/like/dto/request/CreateLikesRequest.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/like/infrastructure/LikesRepository.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/shorts/application/VideoValidateService.java
  src/main/java/com/adregamdi/shorts/domain/Shorts.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
Labels: 🐞 BugFix

#142 [#141] 지금 뜨는 쇼츠 & 인기 있는 여행기 리스트 조회 api
  src/main/java/com/adregamdi/shorts/application/ShortsService.java
  src/main/java/com/adregamdi/shorts/application/ShortsServiceImpl.java
  src/main/java/com/adregamdi/shorts/domain/Shorts.java
  src/main/java/com/adregamdi/shorts/dto/request/CreateShortsRequest.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepository.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
  src/main/java/com/adregamdi/shorts/presentation/ShortsController.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/dto/HotTravelogueDTO.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetHotTraveloguesResponse.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepository.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: ✨ Feature

#144 Bugfix - 테이블 간 memberId 타입 불일치로 인한 버그 수정
  src/main/generated/com/adregamdi/member/domain/QMember.java
  src/main/java/com/adregamdi/core/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adregamdi/core/jwt/service/JwtService.java
  src/main/java/com/adregamdi/core/oauth2/application/OAuth2Service.java
  src/main/java/com/adregamdi/core/oauth2/domain/CustomOAuth2User.java
  src/main/java/com/adregamdi/core/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/member/infrastructure/MemberRepository.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
Labels: 🔨 Refactor, 🐞 BugFix

#145 [#131] 쇼츠 컨텐츠에 장소, 여행기 이미지 추가 & 좋아요한 전체 리스트 버그 픽스
  src/main/java/com/adregamdi/like/dto/ShortsContentDTO.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/search/dto/ShortsSearchDTO.java
  src/main/java/com/adregamdi/search/infrastructure/SearchRepositoryImpl.java
  src/main/java/com/adregamdi/shorts/dto/ShortsDTO.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
Labels: 🔨 Refactor, 🐞 BugFix

#147 [#146] 장소 번호, 여행기 번호 유효성 체크 삭제
  src/main/java/com/adregamdi/shorts/dto/request/CreateShortsRequest.java
Labels: 🔨 Refactor, 🐞 BugFix

#154 Refactor - 여행기 조회 시 작성자 id, 이름, 프로필, 핸들 추가
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetTravelogueResponse.java
Labels: 🔨 Refactor, ⚒️Fix, 📬 API

#156 Refactor - 최적 거리 정렬 API HTTP 메서드 수정
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
Labels: 🔨 Refactor, 📬 API

#158 [#157] 지금 뜨는 쇼츠 목록 조회 안되는 버그 수정
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
Labels: 🔨 Refactor, 🐞 BugFix

#162 [#160] prod 운영 서버 CI/CD 설정
  .github/workflows/pr-build-gradle-prod.yml
  .github/workflows/push-deploy-dev.yml
  .github/workflows/push-deploy-prod.yml
Labels: ⚙ Setting

#161 Feature - 마지막 접속 시간 체크 기능 구현
  src/main/java/com/adregamdi/core/oauth2/application/OAuth2Service.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
Labels: ✨ Feature

#164 [#163] 운영서버 1차 배포
  src/main/java/com/adregamdi/core/oauth2/application/OAuth2Service.java
  src/main/java/com/adregamdi/member/application/MemberService.java
  src/main/java/com/adregamdi/member/domain/Member.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
Labels: 🌏 Deploy

#169 Bugfix - 일정에 많이 추가된 장소 API에서 이미지 조회 버그 수정
  src/main/generated/com/adregamdi/member/domain/QMember.java
  src/main/java/com/adregamdi/place/domain/PlaceReviewImage.java
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepositoryImpl.java
Labels: 🐞 BugFix, 📬 API

#171 BugFix - 사진 리뷰 개수 계산 버그 수정
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepositoryImpl.java
Labels: 🐞 BugFix

#173 BugFix - 여행기 등록 시 안 되던 버그 수정
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/dto/PlaceReviewDTO.java
  src/main/java/com/adregamdi/place/dto/response/GetPlaceReviewResponse.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
Labels: 🐞 BugFix, 📬 API

#175 Bugfix - 여행기 조회, 일정 조회 시 버그 수정
  src/main/java/com/adregamdi/like/dto/TravelogueContentDTO.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travel/dto/response/GetMyTravelResponse.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetTravelogueResponse.java
Labels: 🐞 BugFix, 📬 API

#177 BugFix - 장소 목록 안 뜨던 버그 수정
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/dto/response/GetTravelogueResponse.java
Labels: 🐞 BugFix, 📬 API

#166 [#163] jar파일 전송 위치 분리
  .github/workflows/push-deploy-dev.yml
  .github/workflows/push-deploy-prod.yml
Labels: ⚙ Setting

#179 Refactor - 여행기 등록 시 장소 id 추가
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/domain/TravelogueDay.java
  src/main/java/com/adregamdi/travelogue/domain/TravelogueDayPlaceReview.java
  src/main/java/com/adregamdi/travelogue/dto/request/CreateMyTravelogueRequest.java
Labels: 🔨 Refactor, 🐞 BugFix, 📬 API

#181 [#180] 이미지 리사이징 메타데이터 반영 후 업로드
  build.gradle
  src/main/java/com/adregamdi/media/application/ImageServiceImpl.java
  src/main/java/com/adregamdi/shorts/presentation/ShortsController.java
Labels: 🐞 BugFix

#184 BugFix - 인기 장소 조회 시 사진 리뷰 수 버그 수정
  src/main/java/com/adregamdi/place/infrastructure/PlaceCustomRepositoryImpl.java
Labels: 🐞 BugFix, 📬 API

#186 [#185][BugFix] 쇼츠 삭제 api 엔드포인트 수정
  src/main/java/com/adregamdi/shorts/presentation/ShortsController.java
Labels: 🐞 BugFix

#188 Bugfix - 여행기 조회 API 버그 수정
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
Labels: 🐞 BugFix, 📬 API

#190 Feature - 차단 관련 API, 콘텐츠 조회 시 차단한 유저 필터링 기능 구현
  src/main/generated/com/adregamdi/block/domain/QBlock.java
  src/main/java/com/adregamdi/block/application/BlockService.java
  src/main/java/com/adregamdi/block/domain/Block.java
  src/main/java/com/adregamdi/block/dto/request/DeleteBlockRequest.java
  src/main/java/com/adregamdi/block/dto/response/CreateBlockResponse.java
  src/main/java/com/adregamdi/block/dto/response/GetMyBlockingMembers.java
  src/main/java/com/adregamdi/block/exception/BlockException.java
  src/main/java/com/adregamdi/block/infrastructure/BlockRepository.java
  src/main/java/com/adregamdi/block/presentation/BlockController.java
  src/main/java/com/adregamdi/core/handler/GlobalExceptionHandler.java
  src/main/java/com/adregamdi/like/infrastructure/LikesCustomRepositoryImpl.java
  src/main/java/com/adregamdi/place/application/PlaceService.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/domain/PlaceReview.java
  src/main/java/com/adregamdi/place/domain/PlaceReviewImage.java
  src/main/java/com/adregamdi/place/presentation/PlaceController.java
  src/main/java/com/adregamdi/shorts/infrastructure/ShortsCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travel/application/TravelService.java
  src/main/java/com/adregamdi/travelogue/application/TravelogueService.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepository.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
  src/main/java/com/adregamdi/travelogue/presentation/TravelogueController.java
Labels: ✨ Feature, 📬 API

#192 Refactor - 콘텐츠 조회 응답에 작성자 id, 차단한 회원 이름/프로필/핸들 추가
  src/main/java/com/adregamdi/block/application/BlockService.java
  src/main/java/com/adregamdi/block/dto/BlockDTO.java
  src/main/java/com/adregamdi/block/dto/response/GetMyBlockingMembers.java
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/dto/PlaceReviewDTO.java
  src/main/java/com/adregamdi/travelogue/dto/TravelogueDTO.java
  src/main/java/com/adregamdi/travelogue/infrastructure/TravelogueCustomRepositoryImpl.java
Labels: 🔨 Refactor

#194 Refactor - 허용 urls 토큰 검증 스킵 로직 추가, 로깅 추가
  src/main/java/com/adregamdi/core/config/SecurityConfig.java
  src/main/java/com/adregamdi/core/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/adregamdi/core/jwt/service/JwtService.java
Labels: 🔨 Refactor, 📬 API

#196 BugFix - 차단 해제 안 되는 버그 수정
  src/main/java/com/adregamdi/block/application/BlockService.java
Labels: 🐞 BugFix

#198 BugFix - 장소 등록 시 데이터 일부 안 들어가던 버그 수정
  src/main/java/com/adregamdi/place/application/PlaceServiceImpl.java
  src/main/java/com/adregamdi/place/dto/request/CreatePlaceRequest.java
Labels: 🐞 BugFix, 📬 API
